### ISSUE TITLE
Double slashes are added at the end

### ISSUE THREAD

**Issue by ehmicky** [novemberborn/common-path-prefix#31]
```js
> commonPathPrefix(['a/', 'a/'])
'a//'
```

There probably should be only one slash at the end.

**Comment by novemberborn** [comment]
Agreed.

Is this a regression?

**Comment by ehmicky** [comment]
Hi @novemberborn. I don't know I just started using this module :)

**Comment by novemberborn** [comment]
Ah. I merged some changes recently. I tried upgrading AVA to use the new version and tests broke, hence my question.

**Comment by ehmicky** [comment]
Thanks @novemberborn!
