### ISSUE TITLE
This sometimes does not work on short paths

### ISSUE THREAD

**Issue by ehmicky** [novemberborn/common-path-prefix#32]
The following behavior is a little unexpected to me:

```js
> commonPathPrefix(['a', 'a'])
''
> commonPathPrefix(['a/b', 'a/b'])
'a/b/'
```

**Comment by novemberborn** [comment]
Agreed.

Is this a regression?

**Comment by ehmicky** [comment]
I don't know I just started using this module :)

**Comment by novemberborn** [comment]
Ah, so this isn't a bug as such, but it is confusing.

Your first example doesn't contain a path separator, so the function just returns an empty string. We should instead look through all paths for a separator and fall back to the platform default.

**Comment by ehmicky** [comment]
Thanks! :)
